# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: essence/damage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65ssence/damage.proto\x12\x06\x64\x61mage\"X\n\x08Property\x12\x1c\n\x05\x64\x65lta\x18\x01 \x01(\x0b\x32\r.damage.Delta\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\x0b\n\x03x_v\x18\x04 \x01(\x02\x12\x0b\n\x03y_v\x18\x05 \x01(\x02\"!\n\x05\x44\x65lta\x12\x0b\n\x03x_a\x18\x01 \x01(\x02\x12\x0b\n\x03y_a\x18\x02 \x01(\x02\x42\x1dZ\x1bjormungandr/v2/proto/damageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'essence.damage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\033jormungandr/v2/proto/damage'
  _globals['_PROPERTY']._serialized_start=32
  _globals['_PROPERTY']._serialized_end=120
  _globals['_DELTA']._serialized_start=122
  _globals['_DELTA']._serialized_end=155
# @@protoc_insertion_point(module_scope)
