# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: essence/structure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65ssence/structure.proto\x12\tstructure\"\x82\x01\n\x08Property\x12\x1f\n\x05\x64\x65lta\x18\x01 \x01(\x0b\x32\x10.structure.Delta\x12\x0f\n\x07\x64\x65stroy\x18\x02 \x01(\x08\x12!\n\x06health\x18\x03 \x01(\x0b\x32\x11.structure.Health\x12!\n\x06injury\x18\x04 \x01(\x0b\x32\x11.structure.Injury\"5\n\x06Health\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x02\x12\r\n\x05\x61rmor\x18\x02 \x01(\x02\x12\x0e\n\x06shield\x18\x03 \x01(\x02\"i\n\x06Injury\x12\x11\n\tinjurable\x18\x01 \x01(\x08\x12!\n\x06\x64\x61mage\x18\x02 \x01(\x0b\x32\x11.structure.Health\x12\x10\n\x06radius\x18\x65 \x01(\x01H\x00\x12\x10\n\x06\x64irect\x18\x66 \x01(\x04H\x00\x42\x05\n\x03way\",\n\x05\x44\x65lta\x12#\n\x08health_a\x18\x01 \x01(\x0b\x32\x11.structure.HealthB Z\x1ejormungandr/v2/proto/structureb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'essence.structure_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\036jormungandr/v2/proto/structure'
  _globals['_PROPERTY']._serialized_start=39
  _globals['_PROPERTY']._serialized_end=169
  _globals['_HEALTH']._serialized_start=171
  _globals['_HEALTH']._serialized_end=224
  _globals['_INJURY']._serialized_start=226
  _globals['_INJURY']._serialized_end=331
  _globals['_DELTA']._serialized_start=333
  _globals['_DELTA']._serialized_end=377
# @@protoc_insertion_point(module_scope)
