# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: essence/structure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65ssence/structure.proto\x12\x06struct\"\x82\x01\n\x08Property\x12\x1c\n\x05\x64\x65lta\x18\x01 \x01(\x0b\x32\r.struct.Delta\x12\x0f\n\x07\x64\x65stroy\x18\x02 \x01(\x08\x12\x0e\n\x06health\x18\x03 \x01(\x02\x12\x0e\n\x06struct\x18\x04 \x01(\x02\x12\x0e\n\x06shield\x18\x05 \x01(\x02\x12\x17\n\x0fshield_recovery\x18\x06 \x01(\x02\"F\n\x05\x44\x65lta\x12\x10\n\x08health_a\x18\x01 \x01(\x02\x12\x10\n\x08struct_a\x18\x02 \x01(\x02\x12\x19\n\x11shield_recovery_a\x18\x03 \x01(\x02\x42\x1dZ\x1bjormungandr/v2/proto/structb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'essence.structure_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\033jormungandr/v2/proto/struct'
  _globals['_PROPERTY']._serialized_start=36
  _globals['_PROPERTY']._serialized_end=166
  _globals['_DELTA']._serialized_start=168
  _globals['_DELTA']._serialized_end=238
# @@protoc_insertion_point(module_scope)
