"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Fragment(google.protobuf.message.Message):
    """运动的实体"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DELTA_FIELD_NUMBER: builtins.int
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    X_V_FIELD_NUMBER: builtins.int
    Y_V_FIELD_NUMBER: builtins.int
    @property
    def delta(self) -> global___Delta: ...
    x: builtins.float
    y: builtins.float
    x_v: builtins.float
    y_v: builtins.float
    def __init__(
        self,
        *,
        delta: global___Delta | None = ...,
        x: builtins.float = ...,
        y: builtins.float = ...,
        x_v: builtins.float = ...,
        y_v: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["delta", b"delta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["delta", b"delta", "x", b"x", "x_v", b"x_v", "y", b"y", "y_v", b"y_v"]) -> None: ...

global___Fragment = Fragment

@typing_extensions.final
class Delta(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_A_FIELD_NUMBER: builtins.int
    Y_A_FIELD_NUMBER: builtins.int
    x_a: builtins.float
    y_a: builtins.float
    def __init__(
        self,
        *,
        x_a: builtins.float = ...,
        y_a: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["x_a", b"x_a", "y_a", b"y_a"]) -> None: ...

global___Delta = Delta
