// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: essence/structure.proto

package _struct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Property struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delta          *Delta  `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Destroy        bool    `protobuf:"varint,2,opt,name=destroy,proto3" json:"destroy,omitempty"`                                      // 是否摧毁(结构系统而言) 换言之没有struct属性的实体不会被摧毁
	Health         float32 `protobuf:"fixed32,3,opt,name=health,proto3" json:"health,omitempty"`                                       // 生命值
	Struct         float32 `protobuf:"fixed32,4,opt,name=struct,proto3" json:"struct,omitempty"`                                       // 护甲值
	Shield         float32 `protobuf:"fixed32,5,opt,name=shield,proto3" json:"shield,omitempty"`                                       // 护盾值
	ShieldRecovery float32 `protobuf:"fixed32,6,opt,name=shield_recovery,json=shieldRecovery,proto3" json:"shield_recovery,omitempty"` //护盾回复速度
}

func (x *Property) Reset() {
	*x = Property{}
	if protoimpl.UnsafeEnabled {
		mi := &file_essence_structure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_essence_structure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_essence_structure_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetDelta() *Delta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *Property) GetDestroy() bool {
	if x != nil {
		return x.Destroy
	}
	return false
}

func (x *Property) GetHealth() float32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Property) GetStruct() float32 {
	if x != nil {
		return x.Struct
	}
	return 0
}

func (x *Property) GetShield() float32 {
	if x != nil {
		return x.Shield
	}
	return 0
}

func (x *Property) GetShieldRecovery() float32 {
	if x != nil {
		return x.ShieldRecovery
	}
	return 0
}

type Delta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HealthA         float32 `protobuf:"fixed32,1,opt,name=health_a,json=healthA,proto3" json:"health_a,omitempty"`                           // 生命变化值
	StructA         float32 `protobuf:"fixed32,2,opt,name=struct_a,json=structA,proto3" json:"struct_a,omitempty"`                           // 护甲变化值
	ShieldRecoveryA float32 `protobuf:"fixed32,3,opt,name=shield_recovery_a,json=shieldRecoveryA,proto3" json:"shield_recovery_a,omitempty"` // 护盾回复修正系数
}

func (x *Delta) Reset() {
	*x = Delta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_essence_structure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_essence_structure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_essence_structure_proto_rawDescGZIP(), []int{1}
}

func (x *Delta) GetHealthA() float32 {
	if x != nil {
		return x.HealthA
	}
	return 0
}

func (x *Delta) GetStructA() float32 {
	if x != nil {
		return x.StructA
	}
	return 0
}

func (x *Delta) GetShieldRecoveryA() float32 {
	if x != nil {
		return x.ShieldRecoveryA
	}
	return 0
}

var File_essence_structure_proto protoreflect.FileDescriptor

var file_essence_structure_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x22, 0xba, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x23,
	0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52, 0x05, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73,
	0x68, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e,
	0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x22, 0x69,
	0x0a, 0x05, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x5f, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x41, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x41, 0x12, 0x2a, 0x0a,
	0x11, 0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x5f, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x73, 0x68, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x41, 0x42, 0x1d, 0x5a, 0x1b, 0x6a, 0x6f, 0x72,
	0x6d, 0x75, 0x6e, 0x67, 0x61, 0x6e, 0x64, 0x72, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_essence_structure_proto_rawDescOnce sync.Once
	file_essence_structure_proto_rawDescData = file_essence_structure_proto_rawDesc
)

func file_essence_structure_proto_rawDescGZIP() []byte {
	file_essence_structure_proto_rawDescOnce.Do(func() {
		file_essence_structure_proto_rawDescData = protoimpl.X.CompressGZIP(file_essence_structure_proto_rawDescData)
	})
	return file_essence_structure_proto_rawDescData
}

var file_essence_structure_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_essence_structure_proto_goTypes = []interface{}{
	(*Property)(nil), // 0: struct.Property
	(*Delta)(nil),    // 1: struct.Delta
}
var file_essence_structure_proto_depIdxs = []int32{
	1, // 0: struct.Property.delta:type_name -> struct.Delta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_essence_structure_proto_init() }
func file_essence_structure_proto_init() {
	if File_essence_structure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_essence_structure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Property); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_essence_structure_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_essence_structure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_essence_structure_proto_goTypes,
		DependencyIndexes: file_essence_structure_proto_depIdxs,
		MessageInfos:      file_essence_structure_proto_msgTypes,
	}.Build()
	File_essence_structure_proto = out.File
	file_essence_structure_proto_rawDesc = nil
	file_essence_structure_proto_goTypes = nil
	file_essence_structure_proto_depIdxs = nil
}
