// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: essence/base.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	time "jormungandr/v2/proto/time"
	velo "jormungandr/v2/proto/velo"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 哈希字段
	ID    uint64         `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`    // ID
	Time  *time.Property `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"` // 时间
	TimeD *time.Delta    `protobuf:"bytes,4,opt,name=time_d,json=timeD,proto3" json:"time_d,omitempty"`
	Velo  *velo.Property `protobuf:"bytes,5,opt,name=velo,proto3" json:"velo,omitempty"` // 空间
	VeloD *velo.Delta    `protobuf:"bytes,6,opt,name=velo_d,json=veloD,proto3" json:"velo_d,omitempty"`
}

func (x *Entity) Reset() {
	*x = Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_essence_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_essence_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_essence_base_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Entity) GetTime() *time.Property {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Entity) GetTimeD() *time.Delta {
	if x != nil {
		return x.TimeD
	}
	return nil
}

func (x *Entity) GetVelo() *velo.Property {
	if x != nil {
		return x.Velo
	}
	return nil
}

func (x *Entity) GetVeloD() *velo.Delta {
	if x != nil {
		return x.VeloD
	}
	return nil
}

type Space struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity []*Entity `protobuf:"bytes,1,rep,name=entity,proto3" json:"entity,omitempty"`
}

func (x *Space) Reset() {
	*x = Space{}
	if protoimpl.UnsafeEnabled {
		mi := &file_essence_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_essence_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_essence_base_proto_rawDescGZIP(), []int{1}
}

func (x *Space) GetEntity() []*Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

var File_essence_base_proto protoreflect.FileDescriptor

var file_essence_base_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x12, 0x65, 0x73, 0x73, 0x65,
	0x6e, 0x63, 0x65, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16,
	0x65, 0x73, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x74, 0x61, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x44, 0x12, 0x22, 0x0a, 0x04, 0x76, 0x65, 0x6c,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x65, 0x6c, 0x6f, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x04, 0x76, 0x65, 0x6c, 0x6f, 0x12, 0x22, 0x0a,
	0x06, 0x76, 0x65, 0x6c, 0x6f, 0x5f, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x76, 0x65, 0x6c, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52, 0x05, 0x76, 0x65, 0x6c, 0x6f,
	0x44, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x22, 0x2d, 0x0a, 0x05, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x24, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x1b, 0x5a, 0x19, 0x6a, 0x6f, 0x72, 0x6d, 0x75, 0x6e,
	0x67, 0x61, 0x6e, 0x64, 0x72, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_essence_base_proto_rawDescOnce sync.Once
	file_essence_base_proto_rawDescData = file_essence_base_proto_rawDesc
)

func file_essence_base_proto_rawDescGZIP() []byte {
	file_essence_base_proto_rawDescOnce.Do(func() {
		file_essence_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_essence_base_proto_rawDescData)
	})
	return file_essence_base_proto_rawDescData
}

var file_essence_base_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_essence_base_proto_goTypes = []interface{}{
	(*Entity)(nil),        // 0: base.Entity
	(*Space)(nil),         // 1: base.Space
	(*time.Property)(nil), // 2: time.Property
	(*time.Delta)(nil),    // 3: time.Delta
	(*velo.Property)(nil), // 4: velo.Property
	(*velo.Delta)(nil),    // 5: velo.Delta
}
var file_essence_base_proto_depIdxs = []int32{
	2, // 0: base.Entity.time:type_name -> time.Property
	3, // 1: base.Entity.time_d:type_name -> time.Delta
	4, // 2: base.Entity.velo:type_name -> velo.Property
	5, // 3: base.Entity.velo_d:type_name -> velo.Delta
	0, // 4: base.Space.entity:type_name -> base.Entity
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_essence_base_proto_init() }
func file_essence_base_proto_init() {
	if File_essence_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_essence_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_essence_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Space); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_essence_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_essence_base_proto_goTypes,
		DependencyIndexes: file_essence_base_proto_depIdxs,
		MessageInfos:      file_essence_base_proto_msgTypes,
	}.Build()
	File_essence_base_proto = out.File
	file_essence_base_proto_rawDesc = nil
	file_essence_base_proto_goTypes = nil
	file_essence_base_proto_depIdxs = nil
}
