// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: essence/structure.proto

package structure

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Property struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delta   *Delta  `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Destroy bool    `protobuf:"varint,2,opt,name=destroy,proto3" json:"destroy,omitempty"` // 该结构是否摧毁
	Health  *Health `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`    // 生命值
	Injury  *Injury `protobuf:"bytes,4,opt,name=injury,proto3" json:"injury,omitempty"`    // 伤害（其他实体）相关
}

func (x *Property) Reset() {
	*x = Property{}
	if protoimpl.UnsafeEnabled {
		mi := &file_essence_structure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_essence_structure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_essence_structure_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetDelta() *Delta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *Property) GetDestroy() bool {
	if x != nil {
		return x.Destroy
	}
	return false
}

func (x *Property) GetHealth() *Health {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *Property) GetInjury() *Injury {
	if x != nil {
		return x.Injury
	}
	return nil
}

type Health struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body   float32 `protobuf:"fixed32,1,opt,name=body,proto3" json:"body,omitempty"`     // 实体本身
	Armor  float32 `protobuf:"fixed32,2,opt,name=armor,proto3" json:"armor,omitempty"`   // 护甲
	Shield float32 `protobuf:"fixed32,3,opt,name=shield,proto3" json:"shield,omitempty"` // 护盾
}

func (x *Health) Reset() {
	*x = Health{}
	if protoimpl.UnsafeEnabled {
		mi := &file_essence_structure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_essence_structure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_essence_structure_proto_rawDescGZIP(), []int{1}
}

func (x *Health) GetBody() float32 {
	if x != nil {
		return x.Body
	}
	return 0
}

func (x *Health) GetArmor() float32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *Health) GetShield() float32 {
	if x != nil {
		return x.Shield
	}
	return 0
}

type Injury struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Injurable bool    `protobuf:"varint,1,opt,name=injurable,proto3" json:"injurable,omitempty"` // 是否可伤害其他实体
	Damage    *Health `protobuf:"bytes,2,opt,name=damage,proto3" json:"damage,omitempty"`        // 造成伤害的数值
	// Types that are assignable to Way:
	//
	//	*Injury_Radius
	//	*Injury_Direct
	Way isInjury_Way `protobuf_oneof:"way"`
}

func (x *Injury) Reset() {
	*x = Injury{}
	if protoimpl.UnsafeEnabled {
		mi := &file_essence_structure_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Injury) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Injury) ProtoMessage() {}

func (x *Injury) ProtoReflect() protoreflect.Message {
	mi := &file_essence_structure_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Injury.ProtoReflect.Descriptor instead.
func (*Injury) Descriptor() ([]byte, []int) {
	return file_essence_structure_proto_rawDescGZIP(), []int{2}
}

func (x *Injury) GetInjurable() bool {
	if x != nil {
		return x.Injurable
	}
	return false
}

func (x *Injury) GetDamage() *Health {
	if x != nil {
		return x.Damage
	}
	return nil
}

func (m *Injury) GetWay() isInjury_Way {
	if m != nil {
		return m.Way
	}
	return nil
}

func (x *Injury) GetRadius() float64 {
	if x, ok := x.GetWay().(*Injury_Radius); ok {
		return x.Radius
	}
	return 0
}

func (x *Injury) GetDirect() uint64 {
	if x, ok := x.GetWay().(*Injury_Direct); ok {
		return x.Direct
	}
	return 0
}

type isInjury_Way interface {
	isInjury_Way()
}

type Injury_Radius struct {
	Radius float64 `protobuf:"fixed64,101,opt,name=radius,proto3,oneof"` // 范围伤害的范围
}

type Injury_Direct struct {
	Direct uint64 `protobuf:"varint,102,opt,name=direct,proto3,oneof"` // 直接伤害的目标ID
}

func (*Injury_Radius) isInjury_Way() {}

func (*Injury_Direct) isInjury_Way() {}

type Delta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HealthA *Health `protobuf:"bytes,1,opt,name=health_a,json=healthA,proto3" json:"health_a,omitempty"` // 生命变化值
}

func (x *Delta) Reset() {
	*x = Delta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_essence_structure_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_essence_structure_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_essence_structure_proto_rawDescGZIP(), []int{3}
}

func (x *Delta) GetHealthA() *Health {
	if x != nil {
		return x.HealthA
	}
	return nil
}

var File_essence_structure_proto protoreflect.FileDescriptor

var file_essence_structure_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x22, 0xa2, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x12, 0x26, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x74, 0x61, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73,
	0x74, 0x72, 0x6f, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74,
	0x72, 0x6f, 0x79, 0x12, 0x29, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x29,
	0x0a, 0x06, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x49, 0x6e, 0x6a, 0x75, 0x72,
	0x79, 0x52, 0x06, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x79, 0x22, 0x4a, 0x0a, 0x06, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x6d, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73,
	0x68, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x06, 0x49, 0x6e, 0x6a, 0x75, 0x72, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x6e, 0x6a, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x29,
	0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x72, 0x61, 0x64,
	0x69, 0x75, 0x73, 0x18, 0x65, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x72, 0x61, 0x64,
	0x69, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x06, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x66, 0x20,
	0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x42, 0x05, 0x0a,
	0x03, 0x77, 0x61, 0x79, 0x22, 0x35, 0x0a, 0x05, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x2c, 0x0a,
	0x08, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x52, 0x07, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x41, 0x42, 0x20, 0x5a, 0x1e, 0x6a,
	0x6f, 0x72, 0x6d, 0x75, 0x6e, 0x67, 0x61, 0x6e, 0x64, 0x72, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_essence_structure_proto_rawDescOnce sync.Once
	file_essence_structure_proto_rawDescData = file_essence_structure_proto_rawDesc
)

func file_essence_structure_proto_rawDescGZIP() []byte {
	file_essence_structure_proto_rawDescOnce.Do(func() {
		file_essence_structure_proto_rawDescData = protoimpl.X.CompressGZIP(file_essence_structure_proto_rawDescData)
	})
	return file_essence_structure_proto_rawDescData
}

var file_essence_structure_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_essence_structure_proto_goTypes = []interface{}{
	(*Property)(nil), // 0: structure.Property
	(*Health)(nil),   // 1: structure.Health
	(*Injury)(nil),   // 2: structure.Injury
	(*Delta)(nil),    // 3: structure.Delta
}
var file_essence_structure_proto_depIdxs = []int32{
	3, // 0: structure.Property.delta:type_name -> structure.Delta
	1, // 1: structure.Property.health:type_name -> structure.Health
	2, // 2: structure.Property.injury:type_name -> structure.Injury
	1, // 3: structure.Injury.damage:type_name -> structure.Health
	1, // 4: structure.Delta.health_a:type_name -> structure.Health
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_essence_structure_proto_init() }
func file_essence_structure_proto_init() {
	if File_essence_structure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_essence_structure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Property); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_essence_structure_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Health); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_essence_structure_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Injury); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_essence_structure_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Delta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_essence_structure_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Injury_Radius)(nil),
		(*Injury_Direct)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_essence_structure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_essence_structure_proto_goTypes,
		DependencyIndexes: file_essence_structure_proto_depIdxs,
		MessageInfos:      file_essence_structure_proto_msgTypes,
	}.Build()
	File_essence_structure_proto = out.File
	file_essence_structure_proto_rawDesc = nil
	file_essence_structure_proto_goTypes = nil
	file_essence_structure_proto_depIdxs = nil
}
