# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 00_meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import 10_time_pb2 as 10__time__pb2
import 11_velocity_pb2 as 11__velocity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\r00_meta.proto\x12\x04meta\x1a\r10_time.proto\x1a\x11\x31\x31_velocity.proto\"P\n\x06\x45ntity\x12\n\n\x02ID\x18\x01 \x01(\x04\x12\x1c\n\x04time\x18\x02 \x01(\x0b\x32\x0e.time.Fragment\x12\x1c\n\x04velo\x18\x03 \x01(\x0b\x32\x0e.velo.Fragment\"%\n\x05\x46ield\x12\x1c\n\x06\x65ntity\x18\x01 \x03(\x0b\x32\x0c.meta.EntityB\x1bZ\x19jormungandr/v2/proto/metab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '00_meta_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031jormungandr/v2/proto/meta'
  _globals['_ENTITY']._serialized_start=57
  _globals['_ENTITY']._serialized_end=137
  _globals['_FIELD']._serialized_start=139
  _globals['_FIELD']._serialized_end=176
# @@protoc_insertion_point(module_scope)
