# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 10_time.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\r10_time.proto\x12\x04time\"\"\n\x04Time\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x04\x12\r\n\x05speed\x18\x02 \x01(\x04\x42\x1bZ\x19jormungandr/v2/proto/timeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '10_time_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031jormungandr/v2/proto/time'
  _globals['_TIME']._serialized_start=23
  _globals['_TIME']._serialized_end=57
# @@protoc_insertion_point(module_scope)
