# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 11_velocity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x31\x31_velocity.proto\x12\x04velo\"T\n\x08Velocity\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0b\n\x03x_v\x18\x03 \x01(\x02\x12\x0b\n\x03y_v\x18\x04 \x01(\x02\x12\x0b\n\x03x_a\x18\x05 \x01(\x02\x12\x0b\n\x03y_a\x18\x06 \x01(\x02\x42\x1bZ\x19jormungandr/v2/proto/velob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '11_velocity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031jormungandr/v2/proto/velo'
  _globals['_VELOCITY']._serialized_start=27
  _globals['_VELOCITY']._serialized_end=111
# @@protoc_insertion_point(module_scope)
