# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import base_pb2
import service_pb2


class ContinuumBase(abc.ABC):

    @abc.abstractmethod
    async def TimePass(self, stream: 'grpclib.server.Stream[service_pb2.Request, service_pb2.Result]') -> None:
        pass

    @abc.abstractmethod
    async def VelocityMove(self, stream: 'grpclib.server.Stream[service_pb2.Request, service_pb2.Result]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/continuum.Continuum/TimePass': grpclib.const.Handler(
                self.TimePass,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.Request,
                service_pb2.Result,
            ),
            '/continuum.Continuum/VelocityMove': grpclib.const.Handler(
                self.VelocityMove,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.Request,
                service_pb2.Result,
            ),
        }


class ContinuumStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.TimePass = grpclib.client.UnaryUnaryMethod(
            channel,
            '/continuum.Continuum/TimePass',
            service_pb2.Request,
            service_pb2.Result,
        )
        self.VelocityMove = grpclib.client.UnaryUnaryMethod(
            channel,
            '/continuum.Continuum/VelocityMove',
            service_pb2.Request,
            service_pb2.Result,
        )
