# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import velocity_pb2 as velocity__pb2


class ContinuumStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VectorModule = channel.unary_unary(
                '/continuum.Continuum/VectorModule',
                request_serializer=velocity__pb2.Request.SerializeToString,
                response_deserializer=velocity__pb2.Result.FromString,
                )


class ContinuumServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VectorModule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContinuumServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VectorModule': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorModule,
                    request_deserializer=velocity__pb2.Request.FromString,
                    response_serializer=velocity__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'continuum.Continuum', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Continuum(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VectorModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/continuum.Continuum/VectorModule',
            velocity__pb2.Request.SerializeToString,
            velocity__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
