# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import velocity_pb2 as velocity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tcontinuum\x1a\x0evelocity.proto28\n\tContinuum\x12+\n\x0cVectorModule\x12\r.velo.Request\x1a\x0c.velo.ResultB\x16Z\x14\x61tom/proto/continuumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024atom/proto/continuum'
  _globals['_CONTINUUM']._serialized_start=44
  _globals['_CONTINUUM']._serialized_end=100
# @@protoc_insertion_point(module_scope)
