# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tcontinuum\x1a\nbase.proto\"8\n\x07Request\x12\x11\n\tnest_tick\x18\x01 \x01(\r\x12\x1a\n\x05\x66ield\x18\x02 \x01(\x0b\x32\x0b.base.Field\"&\n\x06Result\x12\x1c\n\x07history\x18\x01 \x03(\x0b\x32\x0b.base.Field2u\n\tContinuum\x12\x31\n\x08TimePass\x12\x12.continuum.Request\x1a\x11.continuum.Result\x12\x35\n\x0cVelocityMove\x12\x12.continuum.Request\x1a\x11.continuum.ResultB Z\x1ejormungandr/v2/proto/continuumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\036jormungandr/v2/proto/continuum'
  _globals['_REQUEST']._serialized_start=40
  _globals['_REQUEST']._serialized_end=96
  _globals['_RESULT']._serialized_start=98
  _globals['_RESULT']._serialized_end=136
  _globals['_CONTINUUM']._serialized_start=138
  _globals['_CONTINUUM']._serialized_end=255
# @@protoc_insertion_point(module_scope)
