# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntime.proto\x12\x04time\"B\n\x08\x46ragment\x12\x1a\n\x05\x64\x65lta\x18\x01 \x01(\x0b\x32\x0b.time.Delta\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x04\x12\r\n\x05speed\x18\x03 \x01(\x04\"\x17\n\x05\x44\x65lta\x12\x0e\n\x06time_a\x18\x01 \x01(\x04\x42\x1bZ\x19jormungandr/v2/proto/timeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031jormungandr/v2/proto/time'
  _globals['_FRAGMENT']._serialized_start=20
  _globals['_FRAGMENT']._serialized_end=86
  _globals['_DELTA']._serialized_start=88
  _globals['_DELTA']._serialized_end=111
# @@protoc_insertion_point(module_scope)
