# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: velocity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evelocity.proto\x12\x04velo\"V\n\x08\x46ragment\x12\x1a\n\x05\x64\x65lta\x18\x01 \x01(\x0b\x32\x0b.velo.Delta\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\x0b\n\x03x_v\x18\x04 \x01(\x02\x12\x0b\n\x03y_v\x18\x05 \x01(\x02\"!\n\x05\x44\x65lta\x12\x0b\n\x03x_a\x18\x01 \x01(\x02\x12\x0b\n\x03y_a\x18\x02 \x01(\x02\x42\x1bZ\x19jormungandr/v2/proto/velob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'velocity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031jormungandr/v2/proto/velo'
  _globals['_FRAGMENT']._serialized_start=24
  _globals['_FRAGMENT']._serialized_end=110
  _globals['_DELTA']._serialized_start=112
  _globals['_DELTA']._serialized_end=145
# @@protoc_insertion_point(module_scope)
