# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: velocity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evelocity.proto\x12\x04velo\"R\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0b\n\x03x_v\x18\x03 \x01(\x02\x12\x0b\n\x03y_v\x18\x04 \x01(\x02\x12\x0b\n\x03x_a\x18\x05 \x01(\x02\x12\x0b\n\x03y_a\x18\x06 \x01(\x02\"+\n\nVectorList\x12\x1d\n\x07vectors\x18\x01 \x03(\x0b\x32\x0c.velo.Vector\"=\n\x07Request\x12\x11\n\tnest_tick\x18\x01 \x01(\r\x12\x1f\n\x05space\x18\x02 \x01(\x0b\x32\x10.velo.VectorList\"+\n\x06Result\x12!\n\x07history\x18\x01 \x03(\x0b\x32\x10.velo.VectorListB\x11Z\x0f\x61tom/proto/velob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'velocity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017atom/proto/velo'
  _globals['_VECTOR']._serialized_start=24
  _globals['_VECTOR']._serialized_end=106
  _globals['_VECTORLIST']._serialized_start=108
  _globals['_VECTORLIST']._serialized_end=151
  _globals['_REQUEST']._serialized_start=153
  _globals['_REQUEST']._serialized_end=214
  _globals['_RESULT']._serialized_start=216
  _globals['_RESULT']._serialized_end=259
# @@protoc_insertion_point(module_scope)
