// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: 10_time.proto

package time

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Time struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age   uint64 `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Speed uint64 `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *Time) Reset() {
	*x = Time{}
	if protoimpl.UnsafeEnabled {
		mi := &file__10_time_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Time) ProtoMessage() {}

func (x *Time) ProtoReflect() protoreflect.Message {
	mi := &file__10_time_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Time.ProtoReflect.Descriptor instead.
func (*Time) Descriptor() ([]byte, []int) {
	return file__10_time_proto_rawDescGZIP(), []int{0}
}

func (x *Time) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Time) GetSpeed() uint64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

var File__10_time_proto protoreflect.FileDescriptor

var file__10_time_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x31, 0x30, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x42, 0x1b, 0x5a, 0x19, 0x6a, 0x6f, 0x72, 0x6d, 0x75, 0x6e, 0x67,
	0x61, 0x6e, 0x64, 0x72, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file__10_time_proto_rawDescOnce sync.Once
	file__10_time_proto_rawDescData = file__10_time_proto_rawDesc
)

func file__10_time_proto_rawDescGZIP() []byte {
	file__10_time_proto_rawDescOnce.Do(func() {
		file__10_time_proto_rawDescData = protoimpl.X.CompressGZIP(file__10_time_proto_rawDescData)
	})
	return file__10_time_proto_rawDescData
}

var file__10_time_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file__10_time_proto_goTypes = []interface{}{
	(*Time)(nil), // 0: time.Time
}
var file__10_time_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file__10_time_proto_init() }
func file__10_time_proto_init() {
	if File__10_time_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file__10_time_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Time); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__10_time_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file__10_time_proto_goTypes,
		DependencyIndexes: file__10_time_proto_depIdxs,
		MessageInfos:      file__10_time_proto_msgTypes,
	}.Build()
	File__10_time_proto = out.File
	file__10_time_proto_rawDesc = nil
	file__10_time_proto_goTypes = nil
	file__10_time_proto_depIdxs = nil
}
