// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.3
// source: essence/service.proto

package continuum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContinuumClient is the client API for Continuum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContinuumClient interface {
	Tick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*HistoryResult, error)
}

type continuumClient struct {
	cc grpc.ClientConnInterface
}

func NewContinuumClient(cc grpc.ClientConnInterface) ContinuumClient {
	return &continuumClient{cc}
}

func (c *continuumClient) Tick(ctx context.Context, in *TickRequest, opts ...grpc.CallOption) (*HistoryResult, error) {
	out := new(HistoryResult)
	err := c.cc.Invoke(ctx, "/continuum.Continuum/Tick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContinuumServer is the server API for Continuum service.
// All implementations must embed UnimplementedContinuumServer
// for forward compatibility
type ContinuumServer interface {
	Tick(context.Context, *TickRequest) (*HistoryResult, error)
	mustEmbedUnimplementedContinuumServer()
}

// UnimplementedContinuumServer must be embedded to have forward compatible implementations.
type UnimplementedContinuumServer struct {
}

func (UnimplementedContinuumServer) Tick(context.Context, *TickRequest) (*HistoryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tick not implemented")
}
func (UnimplementedContinuumServer) mustEmbedUnimplementedContinuumServer() {}

// UnsafeContinuumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContinuumServer will
// result in compilation errors.
type UnsafeContinuumServer interface {
	mustEmbedUnimplementedContinuumServer()
}

func RegisterContinuumServer(s grpc.ServiceRegistrar, srv ContinuumServer) {
	s.RegisterService(&Continuum_ServiceDesc, srv)
}

func _Continuum_Tick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContinuumServer).Tick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/continuum.Continuum/Tick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContinuumServer).Tick(ctx, req.(*TickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Continuum_ServiceDesc is the grpc.ServiceDesc for Continuum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Continuum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "continuum.Continuum",
	HandlerType: (*ContinuumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tick",
			Handler:    _Continuum_Tick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "essence/service.proto",
}
